### ISSUE TITLE
Which backpack should I take for a one month interrail journey?

### ISSUE THREAD

**Issue by edwardcodes** [edwardcodes/Around-the-World#4]
Tortuga is the best choice I’ve seen so far, Redwing 44 would be next but it’s too “thin”.

**Comment by nelsonic** [comment]
💡 consider adding product links, images and reviews. 😉 e.g: https://github.com/nelsonic/nelsonic.github.io/issues/418

**Comment by nelsonic** [comment]
Tortuga Setout One: $199 + Shipping from USA ... 😮 
https://www.tortugabackpacks.com/pages/patagonia-mlc-vs-tortuga-setout-backpack
![image](https://user-images.githubusercontent.com/194400/45914658-ef314200-be3f-11e8-98d9-ff22647b4073.png)

Video Review:
[![image](https://user-images.githubusercontent.com/194400/45914647-d0cb4680-be3f-11e8-90d3-32ffabb0fc38.png)](https://youtu.be/64Ym1DbRItE)
https://youtu.be/64Ym1DbRItE

Comparison to Patagonia MLC:
https://www.tortugabackpacks.com/pages/patagonia-mlc-vs-tortuga-setout-backpack
(_slightly "biased" considering it's on the Totuga Blog! but still makes several valid points!_)

**Comment by nelsonic** [comment]
### Decathlon Forclaz Travel 100 _LOCKABLE_ Trekking Backpack 70L Grey €60
https://www.decathlon.pt/mochila-trekking-100-70l-cinza-id_8511742.html
![image](https://user-images.githubusercontent.com/194400/45915101-0fb0ca80-be47-11e8-850e-573ccbbb88bd.png)

### Specification  

I _obviously_ prefer to read product specs in English so here they are:
https://www.decathlon.co.uk/travel-100-70l-backpack-grey-id_8511742.html
![image](https://user-images.githubusercontent.com/194400/45915075-81d4df80-be46-11e8-8b05-b27c4f5cb579.png)

+ Height: 65 cm
+ Width: 40 cm
+ Depth: 30 cm
+ Weight: 1.7 kg

### Review

https://youtu.be/-Mv9ZbsMAvE 
note: this review is for the 50L version 
https://www.decathlon.co.uk/forclaz-50l-hiking-rucksack-grey-id_8300838.html
![image](https://user-images.githubusercontent.com/194400/45915801-7b009980-be53-11e8-9a32-b8ab092b2664.png)
H 62 x W 32 x D 24

(_whereas the link above is for the 70L, which I think is a better option for a longer trip_) 
The bags are _mostly_ the same, the 70L is just "scaled up/down".
The 50L version is _much_ closer to Ryanair's limits. 

### Advantages

+ Price. (_there's no getting around this! it's **by far** the **cheapest** bag in this size_) €
+ Has most if not all the "features" and pockets a traveller could need.
+ ***Lockable***! (_the zips include rings for a lock!_)
+ Lightweight
+ Comfortable design (_backpack straps and back padding_) 
+ Nobody will think you are "rich" as this is a fairly "generic" brand and design.

### Disadvantages 

+ **Exceeds _hight_ restriction** for Airplane Carry on. 😞 
(_although if you needed to, you can simply not "over-fill" it when travelling by plane 
  and it would "fit" in any of the luggage checkers..._) 
+ **Top-loading**. Some people don't like this because you cannot "see everything" at once.
I personally don't have an issue with top-load packing because it forces you to pack in an "order"
and means you can put "dirty laundry" at the bottom (out of the way) 
+ These type of rucksacks _look_ "touristy" ...  but that's the "price" you pay for comfort/utility.

![image](https://user-images.githubusercontent.com/194400/45915944-c9af3300-be55-11e8-97d8-d4c1730ba724.png)

> Top tip: most _international_ e-commerce company websites allow you to change the TLD in the domain to view the product in a different "locale" (language and currency) e.g: 
FROM:
```
https://www.decathlon.co.uk/travel-100-70l-backpack-grey-id_8511742.html
```
TO:
```
https://www.decathlon.pt/travel-100-70l-backpack-grey-id_8511742.html
```
![image](https://user-images.githubusercontent.com/194400/45915099-fb6ccd80-be46-11e8-99b7-0e86e7dae55d.png)

Or _vice-versa_. 
This works for Amazon, Ebay, AirBnB, etc.

## Airplane Carry On Dimensions

@edwardcodes **`while`** your _initial_ adventure is going to be by _rail_ #2 
you will _inevitably_ be getting a _flight_ at some point in the future. 
So it's a _good_ idea to _consider_ the "Maximum Legal Carry ON 

_Most_ travel websites/blogs/vlogs are written by people who use Inches for measurements ... 🇺🇸 🙄 
e.g: https://travel-made-simple.com/carry-on-size-chart
![image](https://user-images.githubusercontent.com/194400/45915225-c150fb00-be49-11e8-8a61-40b7c3d131f5.png)

Inches are _useless_ for _everyone **`else`**_ as _nobody_ in the _rest_ of the world "thinks" in inches. 
see: https://interestingengineering.com/imperial-system-measurement-worst

If you search for: "airline carry on dimensions cm"
https://www.edreams.com/blog/luggage-restrictions-by-airline

Ryanair is the _most_ restrictive 🙄 
https://www.ryanair.com/gb/en/useful-info/help-centre/faq-overview/Baggage
![image](https://user-images.githubusercontent.com/194400/45915471-25c18980-be4d-11e8-97d9-cb8d59793097.png)

+ Height: 55cm
+ Width: 40cm
+ Depth: 20cm 
+ Weight: 10kg

**Comment by nelsonic** [comment]
If you are _researching_ bag _features_ watch this vid: https://youtu.be/ryQsYwyZKB0
Worth making notes of the features you would _like_ (_or need_) to have. 😉

**Comment by edwardcodes** [comment]
I really like the Forclaz 50L!
It has an “important” feature for me that is the lower back “suspension” 🤔

**Comment by nelsonic** [comment]
@edwardcodes yeah, all the Forclaz models are generally well-designed and have "suspension",
_However_ the **50L** is _not_ "Lockable" unless you get the more _expensive_ one:
https://www.decathlon.co.uk/travel-500-50l-w-backpack-blue-id_8383138.html
![image](https://user-images.githubusercontent.com/194400/45923361-06be0880-bedc-11e8-8dcd-1b90746ed510.png)

€79 in PT: https://www.decathlon.pt/travel-500-50l-w-backpack-blue-id_8383138.html
![image](https://user-images.githubusercontent.com/194400/45923366-1f2e2300-bedc-11e8-8c05-144a8664b7c3.png)
Which means you "might as well" get the 70L version which is _cheaper_ at €60! 😮

**Comment by nelsonic** [comment]
# Cabin Max

If your goal is to buy a bag that you can use a Airplane "Carry On",
One of the better options is a "***Cabin Max***" which has the **_exact_ dimensions** for Ryanair.
https://www.amazon.co.uk/Cabin-Max-Backpack-Approved-55x40x20/dp/B002Q5APX4
![image](https://user-images.githubusercontent.com/194400/45923770-e47db800-bee6-11e8-8c7f-8f4099db8d7e.png)

It's ("_only_") **44 Litre** capacity which means you are _forced_ to travel _much_ lighter than you would with a 70L bag. This can be a _really_ good thing for a number of reasons (_see advantages below_)


The _newer_ version of the Cabin Max looks _really_ good:  https://www.amazon.co.uk/dp/B07FF6XG4M/
![image](https://user-images.githubusercontent.com/194400/45923748-56a1cd00-bee6-11e8-8e92-3bf55c37e51d.png)

No reviews yet (_for the new version_) because it was launched _recently_, 
but build quality and both number and _layout_ of pockets looks _better_ than the "original".
It also looks _super_ ***inconspicuous*** (_does not attract any attention_) 

## Advantages

+ The "***perfect***" **size** for travelling by air. (_not the focus for your **current** trip, but it will be in the **near future** when you go **full** "**Digital Nomad**"_) 😉 
+ Good range of **pockets** and two "**grab handles**" (_essential for picking up and "stowing" in overhead_) 
+ **_Padded_ Laptop Pocket** protects your **_income_-generator**.
+ Looks like a "commuter" bag not to a "traveller" backpack. (_good for not calling attention_!)
+ **Carry _less_** "**stuff**" is _generally_ a _great_ principal to follow. (_in travelling and in [**life**](https://github.com/edwardcodes/Around-the-World/issues/1#issuecomment-423537875)_)
  + I used an "Original" Cabin Max for a few years and it was _really_ good for all my short (up to 1 week) business & leisure trips. Though if you have access to a Clothes Washing Machine, you can _easily_ ***live*** out of a 45L bag _long term_. We know several people who do; "Workers". 🙏 
The _only_ reason I decided to "upgrade" to a [45L Patagonia MLC](https://www.patagonia.com/product/black-hole-mlc-convertible-briefcase-45-liters/49305.html) was that the **Zip** "***died***" on the Cabin Max (_probably my fault for "manhandling" it!_) and instead of buying another Cabin Max I wanted a bag that would last me "_the rest of my life_" (_I **never** want to have to buy another bag!_). I feel **45L** it's **_more_ than** "**enough**" space for everything I want to carry (_including: Laptop, 2 Books, Mavic Air Drone, Compact Canon Camera, all Clothes - including exercise gear - and even "spare shoes"!_) I _considered_ getting the [60L "Black Hole" Duffle Bag](https://www.patagonia.com/product/black-hole-duffel-bag-60-liters/49341.html) because it's both cheaper and has more space, but I decided not to because it was "too far" outside the "Carry On" dimensions and our cheapest flights from Porto/LX to London are Ryanair which is quite _strict_ with hand-luggage. 

![image](https://user-images.githubusercontent.com/194400/45924009-d468d700-beec-11e8-90c0-05bced8f3e34.png)
![image](https://user-images.githubusercontent.com/194400/45924011-d92d8b00-beec-11e8-83a9-66f69e9c6e27.png)

## Disadvantages 

+ **Less capacity** than a 70L Forclaz (_much less!_)
  + This can be an _advantage_ because it forces you to pack _much_ lighter which _also_ means you look like less of a "tourist" ("_carrying your house on your shoulders!_") 
  + _However_ having less space means you cannot _realistically_ buy "souvenirs" or "presents" for family members. So you will have to limit yourself to Photos and Postcards (_which are really the **best** souvenirs anyway because they are better for the environment and require no "dusting"!_) 
+ **Shoulder straps** might be _less comfortable_ for longer walks/hikes, though this is _offset_ by the fact that you will be carrying less. From experience, my Cabin Max was "fine" even when I was carrying two laptops and books (_don't tell EasyJet, but I once took 23Kg in Hand luggage!!_) 😉 
+ **No Water Bottle Holder** ... I feel this is not a "deal breaker" as you can always _carry_ your water bottle or "attach" it to the bag using a carabiner or even _string_ e.g: 
![image](https://user-images.githubusercontent.com/194400/45923962-ad5dd580-beeb-11e8-969f-0027e3735af5.png)
![image](https://user-images.githubusercontent.com/194400/45923978-e39b5500-beeb-11e8-9425-269a020c81f3.png)

**Comment by edwardcodes** [comment]
Thank you for the awesome advice!!!
I really like that new version 🤔☀️

**Comment by nelsonic** [comment]
@edwardcodes definitely do a bit more research (_and share your links/images here so we can **all** learn!_) before you decide. I obviously have a _strong_ preference for being able to _lock_ my bag (_considering I always carry a laptop and camera that I would prefer not to lose_...)
But if you feel you are _never_ going to let the bag out of your sigh 
then a bag _without_ a lock could be a viable option.

**Comment by edwardcodes** [comment]
https://www.decathlon.pt/mochila-trekking-travel-500-id_8383137.html

**Comment by nelsonic** [comment]
@edwardcodes FORCLAZ TRAVEL 500 MEN’S LOCKABLE TREKKING BACKPACK 70 LITRES - BLUE
_looks **really good**_!! 😍 
https://www.decathlon.pt/mochila-trekking-travel-500-id_8383137.html
![forclaz-travel-500-70-blue](https://user-images.githubusercontent.com/194400/45939868-8f68a180-bfcd-11e8-860e-daf919ff0446.png)

I _especially_ like the fact that it has a ***detachable*** "**day bag**" at the top:

![forclaz-500-70-detachable-bag](https://user-images.githubusercontent.com/194400/45940124-0e120e80-bfcf-11e8-8052-292992131892.png)

which means you can leave your "main" backpack at the Hostel (_when you are staying somewhere for multiple days and **`if`** **lockers** are available_) and take the _smaller_ (_less "conspicuous"_) bag with you when _exploring_ a city. 🎉 

![forclaz-70-reinforced](https://user-images.githubusercontent.com/194400/45940211-8aa4ed00-bfcf-11e8-89b0-5eb63cff494a.png)

The only "downside" I can see is the _weight_ of the bag: ***2.5Kg*** (_without anything in it!_)
![forclaz-70-weight](https://user-images.githubusercontent.com/194400/45940247-d48dd300-bfcf-11e8-8db9-6ec480b2a8d0.png)

The _weight_ is the result of the _features_ the bag has rather than pointless use of "heavy materials". 💪 
The price seems _reasonable_ considering that it has _many_ functional pockets/storage options. 💡 
If you feel this is "***the one***" (_for you_), go for it! ✅

**Comment by nelsonic** [comment]
@edwardcodes what is the _conclusion_/_decision_ here...? 💭

**Comment by edwardcodes** [comment]
I’m going to buy the Forclaz 500!

**Comment by nelsonic** [comment]
Are you ordering it online or going to the shop so that you can try the neck pillow #7 ?

**Comment by nelsonic** [comment]
@edwardcodes cool. do you have a "ride" to the shop? (e.g: is Avó Lóló taking you or Tia Carol?)

**Comment by edwardcodes** [comment]
@nelsonic
I’m going with a friend because he is going to travel in January six months so it’s a good opportunity to see different backpacks and etc 👍

**Comment by nelsonic** [comment]
Nice. lucky Friend! 🎉
